version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - GRADLE_USER_HOME=/home/gradle/.gradle
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/myreservationreversi
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=user
    depends_on:
      - db
    volumes:
      - gradle-cache:/home/gradle/.gradle

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=myreservationreversi
      - MYSQL_USER=root
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
  gradle-cache:
